---
openapi: 3.0.1
info:
  title: This is swagger tester
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: Login Authentication
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                - token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/api/v1/auth/register":
    post:
      summary: Register Authentication
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                - token
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/api/v1/reservations":
    post:
      summary: create house_booking
      tags:
      - HouseBookings
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                house_id:
                  type: integer
                number_of_days:
                  type: integer
                start_date:
                  type: string
                  format: date
                house_name:
                  type: string
                house_image:
                  type: string
              required:
              - house_id
              - number_of_days
              - start_date
    get:
      summary: list house_bookings
      tags:
      - HouseBookings
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
